version: '3'

networks:
  agh-db:

services:
  neo4j-db:
    image: neo4j:4.2.1-enterprise
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/test
      - NEO4J_apoc_import_file_enabled=true
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_connector_https_advertised__address=localhost:7473
      - NEO4J_dbms_connector_http_advertised__address=localhost:7474
      - NEO4J_dbms_connector_bolt_advertised__address=localhost:7687
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./northwind:/var/lib/neo4j/import/northwind
      - ./cql_scripts/createNorthwind.cql:/createNorthwind.cql
    networks:
      - agh-db
