name: build
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Build back-end image
        run: docker build -t back-end back-end
      - name: Build front-end image
        run: docker build -t front-end back-end
      - name: Start the database, back-end, front-end
        run: docker-compose up -d
      - name: Wait until database is ready
        run: |
          for _ in $(seq 1 20); do
            if curl --output /dev/null --silent --head --fail http://localhost:7474; then
              echo "Database up and running"
              sleep 20
              break;
            fi
            sleep 5
          done
      - name: Install dependencies
        run: cd back-end && npm install
      - name: Run REST API and execute tests
        run: cd back-end && npm run-script run